name: test

on: [push, pull_request]

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '3.0', '3.1', '3.2', jruby, truffleruby ]
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rspec --format p --pattern "spec/**/*_spec.rb"

  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true
    - run: bundle exec rspec --format p --require support/simplecov
    - uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - uses: codacy/codacy-coverage-reporter-action@v1.3.0
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: "coverage/coverage.xml"
